# Generated by Django 3.1.7 on 2021-03-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('company_name', models.CharField(max_length=150)),
                ('interested_in', models.EmailField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('budget', models.IntegerField()),
                ('contact_number', models.CharField(max_length=11)),
                ('about_project', models.TextField()),
                ('file_upload', models.FileField(blank=True, upload_to='files')),
            ],
        ),
    ]
