# Generated by Django 3.1.7 on 2021-03-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='interested_in',
            field=models.CharField(max_length=150),
        ),
    ]
